### ISSUE TITLE
Code problem

### ISSUE THREAD

**Issue by FriedaSmith** [DongyaoZhu/Speech-Recognition#1]
Hello. What is `parse_preprocess()` in `x, _ = parse_preprocess(file, None)`?

**Comment by DongyaoZhu** [comment]
Hi, it was meant to read wav from filename, then build mel spectrogram feature in tensorflow, which is run by sess(tf tensor -> numpy data), then fed to the model for prediction. You could take a look at updated predict.py and utils_data.py. 
Also I worked at this project quite long time ago, so some of the code in tensorflow are really outdated now, especially the data pipelining / save & restore model.

**Comment by FriedaSmith** [comment]
> Hi, it was meant to read wav from filename, then build mel spectrogram feature in tensorflow, which is run by sess(tf tensor -> numpy data), then fed to the model for prediction. You could take a look at updated predict.py and utils_data.py.
> Also I worked at this project quite long time ago, so some of the code in tensorflow are really outdated now, especially the data pipelining / save & restore model.

Thank you for your help.
